import { RequestWithFiles } from "#/middleware/fileParser";
import { categoriesTypes } from "#/models/cards_category";
import { RequestHandler } from "express";
import formidable from "formidable";
import cloudinary from "#/cloud";
import CardsCollection from "#/models/cardsCollection";
import Card from "#/models/card";
import { PopulateFavList } from "#/@types/collection";
import AutogeneratedPlaylist from "#/models/autoGeneratedPlaylist";
import mongoose from "mongoose";
import User from "#/models/User";
import axios from "axios";
import { HUGGING_FACE_API_KEY2, OPENAI_API_KEY } from "#/utils/variables";
import { url } from "inspector";
import PlaylistCollection from "#/models/playlistCollection";

interface createCardsCollectionRequest extends RequestWithFiles {
  body: {
    title: string;
    description: string;
    category: categoriesTypes;
    visibility: "private" | "public";
  };
}

export const createCardsCollection: RequestHandler = async (
  req: createCardsCollectionRequest,
  res
) => {
  const { title, description, category, visibility } = req.body;
  const poster = req.files?.poster as formidable.File;
  const ownerId = req.user.id;
  const exist = await CardsCollection.findOne({
    owner: ownerId,
    title: title,
  });
  if (exist) {
    res.status(422).json({
      error: "user already has the collection",
      message: "collection already exist",
    });
    return;
  }

  if (!title) {
    res.status(422).json({
      error: "missing title",
      message: "title is required to create collection",
    });
    return;
  }

  try {
    const newCollection = await new CardsCollection({
      title,
      description,
      category,
      owner: ownerId,
    });
    if (poster) {
      const posterRes = await cloudinary.uploader.upload(poster.filepath, {
        width: 300,
        height: 300,
        crop: "thumb",
        gravity: "face",
      });
      newCollection.poster = {
        url: posterRes.secure_url,
        publicId: posterRes.public_id,
      };
    }
    if (visibility) {
      newCollection.visibility = visibility;
    }

    await newCollection.save();
    res.status(201).json({
      collection: {
        title,
        description,
        poster: newCollection.poster?.url,
        collectionId: newCollection._id,
        visibility: newCollection?.visibility,
      },
    });
  } catch (err) {
    res.status(500).json({ error: err });
  }
};
// export const CreateCard: RequestHandler = async (req, res) => {
//   const { answer, question, collectionId } = req.body;

//   const ownerId = req.user.id;

//   if (!answer.length || !question.length) {
//     res.status(422).json({
//       error: "missing answer or question",
//       message: "question and answer is required to create card",
//     });
//     return;
//   }

//   try {
//     const exist = await Card.findOne({
//       owner: ownerId,
//       question: question,
//       collectionId: collectionId,
//     });
//     if (exist) {
//       res.status(422).json({
//         error: "user already has the card in his collection",
//         message: "this card already exist in the collection",
//       });
//       return;
//     }

//     const newCard = new Card({
//       question,
//       answer,
//       owner: ownerId,
//       collectionId,
//     });

//     await newCard.save();

//     // Add the new card ID to the collection's cards array
//     const collection = await CardsCollection.findById(collectionId);
//     if (!collection) {
//       res.status(404).json({ error: "Collection not found" });
//       return;
//     }

//     collection.cards.push(
//       newCard._id as unknown as mongoose.Schema.Types.ObjectId
//     );
//     await collection.save();

//     // Populate the collection with the newly added card
//     const updatedCollection = await CardsCollection.findById(
//       collectionId
//     ).populate({
//       path: "cards",
//       select: "_id answer question collectionId",
//     });

//     res.status(201).json({
//       message: "Card added successfully",
//       collection: updatedCollection,
//     });
//   } catch (err) {
//     res.status(500).json({ error: "Internal server error" });
//   }
// };
export const CreateCard: RequestHandler = async (req, res): Promise<void> => {
  const ownerId = req.user.id;
  const { collectionId } = req.body;
  if (!collectionId) {
    console.log("collectionId", collectionId);
    res.status(422).json({
      error: "missing collectionId",
      message: "collectionId is required to create card",
    });
    return;
  }

  let { question = [], answer = [] } = req.body;
  const questionFiles = req.files?.question || [];
  const answerFiles = req.files?.answer || [];

  // Ensure arrays
  if (!Array.isArray(question)) question = Object.values(question);
  if (!Array.isArray(answer)) answer = Object.values(answer);

  try {
    // Limit to 3 each
    if (question.length > 3 || answer.length > 3) {
      res.status(422).json({
        error: "Limit exceeded",
        message: "Only up to 3 questions and 3 answers are allowed",
      });
      return;
    }

    // Combine text + images for questions
    const formattedQuestions = await Promise.all(
      question.map(async (q: any, index: number) => {
        const imageFile = questionFiles?.[index]?.image;
        const imageUrl = imageFile
          ? await cloudinary.uploader.upload(imageFile.filepath)
          : null;

        return {
          text: q.text,
          image: {
            url: imageUrl?.secure_url || null,
            publicId: imageUrl?.public_id || null,
          },
        };
      })
    );

    // Combine text + images for answers
    const formattedAnswers = await Promise.all(
      answer.map(async (a: any, index: number) => {
        const imageFile = answerFiles?.[index]?.image;
        const imageUrl = imageFile
          ? await cloudinary.uploader.upload(imageFile.filepath)
          : null;

        return {
          text: a.text,
          image: {
            url: imageUrl?.secure_url || null,
            publicId: imageUrl?.public_id || null,
          },
        };
      })
    );

    if (!formattedAnswers.length || !formattedQuestions.length) {
      res.status(422).json({
        error: "missing answer or question",
        message: "question and answer are required to create card",
      });
      return;
    }

    const exist = await Card.findOne({
      owner: ownerId,
      question: formattedQuestions,
      collectionId,
    });

    if (exist) {
      res.status(422).json({
        error: "Card exists",
        message: "This card already exists in the collection",
      });
      return;
    }

    const newCard = new Card({
      question: formattedQuestions,
      answer: formattedAnswers,
      owner: ownerId,
      collectionId,
    });

    await newCard.save();

    // Add card to collection
    const collection = await CardsCollection.findById(collectionId);
    if (!collection) {
      res.status(404).json({ error: "Collection not found" });
      return;
    }

    collection.cards.push(
      newCard._id as unknown as mongoose.Schema.Types.ObjectId
    );
    await collection.save();

    const updatedCollection = await CardsCollection.findById(
      collectionId
    ).populate({
      path: "cards",
      select: "_id answer question collectionId",
    });

    res.status(201).json({
      message: "Card added successfully",
      collection: updatedCollection,
    });
  } catch (err) {
    console.error("CreateCard error:", err);
    res.status(500).json({ error: "Internal server error" });
  }
};
export const updateCardsCollection: RequestHandler = async (
  req: createCardsCollectionRequest,
  res
) => {
  const { title, description, category } = req.body;
  const ownerId = req.user.id;
  const poster = req.files?.poster as formidable.File;
  const { CardsCollectionId } = req.params;
  const newCardsCollection = await CardsCollection.findOneAndUpdate(
    {
      owner: ownerId,
      _id: CardsCollectionId,
    },
    {
      title,
      description,
      category,
    },
    {
      new: true,
    }
  );

  if (!newCardsCollection) {
    res.status(404).json({
      error: "Collection not found",
      message: " collection not found ",
    });
    return;
  }
  if (poster) {
    if (newCardsCollection.poster?.publicId) {
      await cloudinary.uploader.destroy(newCardsCollection.poster?.publicId);
    }
    const posterRes = await cloudinary.uploader.upload(poster.filepath, {
      width: 300,
      height: 300,
      crop: "thumb",
      gravity: "face",
    });
    newCardsCollection.poster = {
      url: posterRes.secure_url,
      publicId: posterRes.public_id,
    };
    await newCardsCollection.save();
  }

  res.status(201).json({
    collection: {
      title,
      description,
      poster: newCardsCollection.poster?.url,
      collectionId: newCardsCollection._id,
    },
  });
};
export const updateCard: RequestHandler = async (req, res) => {
  const { answer, question, collectionId } = req.body;
  const ownerId = req.user.id;
  const { cardId } = req.params;
  // const test = req.params;Z
  // console.log({ test, ownerId });
  const newCard = await Card.findOneAndUpdate(
    {
      owner: ownerId,
      _id: cardId,
      collectionId: collectionId,
    },
    {
      answer,
      question,
    },
    {
      new: true,
    }
  );

  if (!newCard) {
    res.status(404).json({
      error: "card not found",
      message: " card not found ",
    });
    return;
  }

  res.status(201).json({
    card: {
      answer,
      question,
      collectionId,
      cardId: newCard._id,
    },
  });
};

export const getCard: RequestHandler = async (req, res) => {
  const { collectionId } = req.params;
  if (!collectionId) {
    res.status(400).json({ error: "Collection ID is required" });
    return;
  }

  try {
    const cards = await Card.find({ collectionId });

    if (!cards.length) {
      res.status(404).json({ error: "No cards found for this collection" });
      return;
    }

    res.json({ cards });
  } catch (err) {
    res.status(500).json({ error: "Internal server error" });
  }
};

export const deleteCard: RequestHandler = async (req, res) => {
  const { collectionId, cardId } = req.params;

  if (!collectionId || !cardId) {
    res.status(400).json({ error: "Collection ID and Card ID are required" });
    return;
  }

  try {
    const card = await Card.findOneAndDelete({ _id: cardId, collectionId });

    if (!card) {
      res.status(404).json({ error: "Card not found in this collection" });
      return;
    }

    // Remove the card ID from the collection's cards array
    const collection = await CardsCollection.findById(collectionId);
    if (collection) {
      collection.cards = collection.cards.filter(
        (card) => card.toString() !== cardId.toString()
      );
      await collection.save();
    }

    res.json({ message: "Card deleted successfully" });
  } catch (err) {
    res.status(500).json({ error: "Internal server error" });
  }
};
export const deleteCollection: RequestHandler = async (req, res) => {
  const { collectionId } = req.params;

  if (!collectionId) {
    res.status(400).json({ error: "Collection ID are required" });
    return;
  }

  try {
    const collection = await CardsCollection.findOneAndDelete({
      _id: collectionId,
    });

    if (!collection) {
      res.status(404).json({ error: "Card not found in this collection" });
      return;
    }

    res.json({ message: "Collection deleted successfully" });
  } catch (err) {
    res.status(500).json({ error: "Internal server error" });
  }
};
export const getLatestCollection: RequestHandler = async (req, res) => {
  const list = await CardsCollection.find({ visibility: "public" })
    .sort("-createdAt")
    .limit(10)
    .populate<PopulateFavList>("owner");

  const collection = list.map((item) => {
    return {
      id: item._id,
      title: item.title,
      description: item.description,
      category: item.category,
      poster: item.poster?.url,
      owner: {
        name: item.owner.name,
        id: item.owner._id,
        avatar: item.owner.avatar?.url || null,
      },
      createdAt: item.createdAt, // Include the creation date
      bookmarks: item.bookmarks.length, // Include the number of bookmarks
      likes: item.likes.length, // Include the number of likes
    };
  });

  res.json({ collection });
};

export const getCollectionWithCards: RequestHandler = async (req, res) => {
  const { collectionId } = req.params;

  if (!collectionId) {
    res.status(400).json({ error: "Collection ID is required" });
    return;
  }

  try {
    const collection = await CardsCollection.findById(collectionId)
      .populate({
        path: "cards",
        select: "_id answer question collectionId",
      })
      .populate<PopulateFavList>({
        path: "owner",
        select: "name email followers followings avatar verified _id", // Specify the fields you want to select
      }); // Populate the owner field;

    if (!collection) {
      res.status(404).json({ error: "Collection not found" });
      return;
    }

    res.json(collection);
  } catch (err) {
    res.status(500).json({ error: "Internal server error" });
  }
};
export const getPlaylistCollectionWithCards: RequestHandler = async (req, res) => {
  const { collectionId } = req.params;

  if (!collectionId) {
    res.status(400).json({ error: "Collection ID is required" });
    return;
  }

  try {
    const collection = await PlaylistCollection.findById(collectionId)
      .populate({
        path: "cards",
        select: "_id answer question collectionId",
      })
      .populate<PopulateFavList>({
        path: "owner",
        select: "name email followers followings avatar verified _id", // Specify the fields you want to select
      }); // Populate the owner field;

    if (!collection) {
      res.status(404).json({ error: "Collection not found" });
      return;
    }

    res.json(collection);
  } catch (err) {
    res.status(500).json({ error: "Internal server error" });
  }
};
// suggested collection controller

export const getSuggestedCollections: RequestHandler = async (req, res) => {
  const userId = req.user.id;

  try {
    // Fetch collections excluding those recently played by the user
    const recentlyPlayedCollections = await AutogeneratedPlaylist.find({
      user: userId,
    }).distinct("collectionId");

    const suggestedCollections = await CardsCollection.find({
      _id: { $nin: recentlyPlayedCollections },
      visibility: "public", // Only suggest public collections
    })
      .sort({ likes: -1 }) // Sort by popularity or any other criteria
      .limit(7)
      .populate<PopulateFavList>("owner");

    const collections = suggestedCollections.map((item) => {
      return {
        id: item._id,
        title: item.title,
        description: item.description,
        category: item.category,
        poster: item.poster?.url,
        owner: {
          name: item.owner.name,
          id: item.owner._id,
          avatar: item.owner.avatar?.url,
        },
      };
    });

    res.json({ collections });
  } catch (err) {
    res.status(500).json({ error: "Internal server error" });
  }
};
// get likes in collection
export const getCollectionLikes: RequestHandler = async (req, res) => {
  const { collectionId } = req.params;

  try {
    const collection = await CardsCollection.findById(collectionId);

    if (!collection) {
      res.status(404).json({ error: "Collection not found" });
      return;
    }

    const totalLikes = collection.likes.length;

    res.json({ totalLikes });
  } catch (err) {
    res.status(500).json({ error: "Internal server error" });
  }
};
// check user likes
export const checkUserLikeStatus: RequestHandler = async (req, res) => {
  const { collectionId } = req.params;
  const userId = req.user.id; // Assuming you have middleware that sets req.user
  const hasUserLikedCollection = async (
    userId: string,
    collectionId: string
  ): Promise<boolean> => {
    try {
      const collection = await CardsCollection.findById(collectionId);
      if (!collection) return false; // If collection doesn't exist, return false

      return collection.likes.some((id) => id.toString() === userId.toString());
    } catch (error) {
      console.error("Error checking like status:", error);
      return false;
    }
  };
  try {
    const isLiked = await hasUserLikedCollection(userId, collectionId);
    res.json({ liked: isLiked });
  } catch (error) {
    res.status(500).json({ error: "Internal server error" });
  }
};

export const handleLikeCollection = async (req: any, res: any) => {
  const { collectionId } = req.params;
  const userId = req.user.id;
  let status: "liked" | "unLiked";
  try {
    const collection = await CardsCollection.findById(collectionId);

    if (!collection) {
      return res.status(404).json({ error: "Collection not found" });
    }

    const isLiked = collection.likes.includes(userId);

    if (isLiked) {
      // Unlike the collection
      collection.likes = collection.likes.filter(
        (id) => id.toString() !== userId.toString()
      ); // Use filter to remove the userId
      await collection.save();
      status = "unLiked";
    } else {
      // Like the collection
      collection.likes.push(userId);
      await collection.save();
      status = "liked";
    }
    res.json({ status });
  } catch (err) {
    res.status(500).json({ error: "Internal server error" });
  }
};

export const CreateBulkCards = async (req: any, res: any) => {
  const { cards, collectionId } = req.body;
  const ownerId = req.user.id;
  if (!Array.isArray(cards) || cards.length === 0) {
    return res
      .status(400)
      .json({ error: "Cards array is required and must not be empty" });
  }

  if (!collectionId) {
    return res.status(400).json({ error: "Collection ID is required" });
  }

  try {
    const newCards = [];

    for (const cardData of cards) {
      const { question, answer } = cardData;

      if (!question || !answer) {
        return res.status(400).json({
          error: "Question and answer are required for each card",
        });
      }

      const exist = await Card.findOne({
        owner: ownerId,
        question: question,
        collectionId: collectionId,
      });

      if (!exist) {
        const newCard = new Card({
          question,
          answer,
          owner: ownerId,
          collectionId,
        });
        await newCard.save();
        newCards.push(newCard._id);
      }
    }

    // Add the new card IDs to the collection's cards array
    const collection = await CardsCollection.findById(collectionId);
    if (!collection) {
      return res.status(404).json({ error: "Collection not found" });
    }

    collection.cards.push(
      ...(newCards as unknown as mongoose.Schema.Types.ObjectId[])
    );
    await collection.save();

    // Populate the collection with the newly added cards
    const updatedCollection = await CardsCollection.findById(
      collectionId
    ).populate({
      path: "cards",
      select: "_id answer question collectionId",
    });

    res.status(201).json({
      message: "Cards added successfully",
      collection: updatedCollection,
    });
    return;
  } catch (err) {
    console.log(err);
    return res.status(500).json({ error: "Internal server error" });
  }
};
export const CreateAiCards = async (req: any, res: any) => {
  const { topic, prompt } = req.body;

  if (!topic || !prompt) {
    return res.status(400).json({ error: "Topic and prompt are required." });
  }

  try {
    const response = await axios.post(
      "https://api.openai.com/v1/chat/completions",
      {
        model: "gpt-4",
        messages: [
          {
            role: "system",
            content:
              "You are an AI that generates educational flashcards based on user prompts.",
          },
          {
            role: "user",
            content: `Create random number of flashcards about ${topic}. Each flashcard should have a question and an answer. ${prompt}`,
          },
        ],
        temperature: 0.7,
        max_tokens: 500,
      },
      {
        headers: { Authorization: `Bearer ${OPENAI_API_KEY}` },
      }
    );

    // Extract AI response and format as an array
    const textResponse = response.data.choices[0].message.content;

    // Convert AI response into JSON format
    let flashcards = [];
    const lines = textResponse
      .split("\n")
      .filter((line: string) => line.trim() !== "");

    for (let i = 0; i < lines.length; i += 2) {
      if (lines[i] && lines[i + 1]) {
        flashcards.push({
          question: lines[i].replace("Q:", "").trim(),
          answer: lines[i + 1].replace("A:", "").trim(),
        });
      }
    }

    res.json(flashcards);
  } catch (error: any) {
    console.error("Error generating flashcards:", error.data);
    res.status(500).json({ error: "Failed to generate flashcards" });
  }
};



export const generateHuggingFace = async (req: any, res: any) => {
  try {
    const { prompt } = req.body;

    // Validate the prompt
    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required" });
    }

    // Construct a detailed prompt for the AI
    const aiPrompt = `
      Create 5 flashcards about ${prompt} in strict JSON format.
      The output MUST be a valid JSON array of objects.
      Each object should have a "question" and an "answer" key.
      Do NOT include any extra text or explanations before or after the JSON. Just the JSON, return the array only.
      Example: [{"question": "What is React?", "answer": "A JavaScript library for building user interfaces"}], don't add anything else to it
    `;

    // Call the AI API (e.g., Hugging Face)
    const response = await axios.post(
      "https://api-inference.huggingface.co/models/mistralai/Mixtral-8x7B-Instruct-v0.1",
      { inputs: aiPrompt },
      { headers: { Authorization: `Bearer ${HUGGING_FACE_API_KEY2}` } }
    );

    // Extract and clean the JSON response
    const rawText = response.data[0].generated_text;
    console.log("Raw Response:", rawText);

    try {
      // Extract the JSON array from the raw text
      const jsonStartIndex = rawText.indexOf("[");
      const jsonEndIndex = rawText.lastIndexOf("]") + 1;

      if (jsonStartIndex === -1 || jsonEndIndex === -1) {
        throw new Error("No valid JSON array found in the response");
      }

      let cleanedJsonString = rawText.substring(jsonStartIndex, jsonEndIndex);

      // Remove extra spaces and newlines
      cleanedJsonString = cleanedJsonString.replace(/\s+/g, " ").trim();

      // Replace single quotes with double quotes (if any)
      // cleanedJsonString = cleanedJsonString.replace(/'/g, '"');
      // Remove invalid characters like "******************************************************************"
      cleanedJsonString = cleanedJsonString.replace(/\*+/g, "");
      // Remove any trailing commas (if any)
      cleanedJsonString = cleanedJsonString.replace(/,\s*]/g, "]");
      // console.log("Cleaned JSON String:", cleanedJsonString);
      // Step 1: Remove the outer quotes
      cleanedJsonString = cleanedJsonString.replace(/^"(.*)"$/, "$1");
      // Step 2: Replace invalid escape characters
      cleanedJsonString = cleanedJsonString.replace(/\\"/g, '"');
      // Step 3: Remove extra spaces and newlines
      cleanedJsonString = cleanedJsonString.replace(/\s+/g, " ").trim();
      // Step 4: Combine the arrays into a single array
      const firstArrayEnd = cleanedJsonString.indexOf("}]") + 2;
      const secondArrayStart = cleanedJsonString.indexOf("[", firstArrayEnd);
      const firstArray = cleanedJsonString.substring(0, firstArrayEnd);
      const secondArray = cleanedJsonString.substring(secondArrayStart);
      // Send the response
      res.send(secondArray);
    } catch (parseError) {
      console.error("Error parsing JSON:", parseError);
      console.error("Raw text that failed to parse:", rawText);
      return res.status(500).json({ error: "Failed to parse AI response" });
    }
  } catch (error) {
    console.error("Error:", error);
    res.status(500).json({ error: "Failed to generate flashcards" });
  }
};

// get by categories
export const getPublicCollectionsCategories: RequestHandler = async (
  req,
  res
) => {
  try {
    const { category } = req.body; // Expecting a single category as a string

    if (!category || typeof category !== "string") {
      res.status(400).json({ error: "Category must be a valid string." });
      return;
    }
    // Fetch collections that are public and match the given category
    const publicCollections = await CardsCollection.find({
      visibility: "public",
      category: category,
    });

    res.status(200).json(publicCollections);
  } catch (error) {
    console.error("Error fetching public collections:", error);
    res.status(500).json({ error: "Failed to fetch collections" });
  }
};
// correct and wrong cards

export const updateCorrectCards: RequestHandler = async (req, res) => {
  try {
    const { collectionId, cardId, type } = req.params;

    if (
      !mongoose.Types.ObjectId.isValid(collectionId) ||
      !mongoose.Types.ObjectId.isValid(cardId)
    ) {
      res.status(400).json({ error: "Invalid collectionId or cardId" });
      return;
    }

    const collection = await CardsCollection.findById(collectionId);
    if (!collection) {
      res.status(404).json({ error: "Collection not found" });
      return;
    }

    const cardObjectId = new mongoose.Types.ObjectId(cardId);
    const isAlreadyCorrect = collection.correctCards.some(
      (id) => String(id) === String(cardObjectId)
    );

    if (type === "write") {
      if (!isAlreadyCorrect) {
        collection.correctCards.push(cardId as any);
      }
    } else if (type === "wrong") {
      collection.correctCards = collection.correctCards.filter(
        (id) => String(id) !== String(cardObjectId)
      );
    } else {
      res.status(400).json({ error: "Invalid type parameter" });
      return;
    }

    // Move correctCards to the back of the cards array
    const correctSet = new Set(collection.correctCards.map(String));
    collection.cards = [
      ...collection.cards.filter((id) => !correctSet.has(String(id))),
      ...collection.correctCards,
    ];

    await collection.save();
    res.json({ message: "Card updated successfully", collection });
    return;
  } catch (error) {
    console.error("Error updating correct cards:", error);
    res.status(500).json({ error: "Internal server error" });
    return;
  }
};

// HANDLE CORRECT CARDS
