import { RequestWithFiles } from "#/middleware/fileParser";
import { categoriesTypes } from "#/models/cards_category";
import { RequestHandler } from "express";
import formidable from "formidable";
import cloudinary from "#/cloud";
import CardsCollection from "#/models/cardsCollection";
import Card from "#/models/card";
import { PopulateFavList } from "#/@types/collection";
import AutogeneratedPlaylist from "#/models/autoGeneratedPlaylist";
import mongoose from "mongoose";

interface createCardsCollectionRequest extends RequestWithFiles {
  body: {
    title: string;
    description: string;
    category: categoriesTypes;
    visibility: "private" | "public";
  };
}

export const createCardsCollection: RequestHandler = async (
  req: createCardsCollectionRequest,
  res
) => {
  const { title, description, category, visibility } = req.body;
  const poster = req.files?.poster as formidable.File;
  const ownerId = req.user.id;
  const exist = await CardsCollection.findOne({
    owner: ownerId,
    title: title,
  });
  if (exist) {
    res.status(422).json({
      error: "user already has the collection",
      message: "collection already exist",
    });
    return;
  }

  if (!title) {
    res.status(422).json({
      error: "missing title",
      message: "title is required to create collection",
    });
    return;
  }

  try {
    const newCollection = await new CardsCollection({
      title,
      description,
      category,
      owner: ownerId,
    });
    if (poster) {
      const posterRes = await cloudinary.uploader.upload(poster.filepath, {
        width: 300,
        height: 300,
        crop: "thumb",
        gravity: "face",
      });
      newCollection.poster = {
        url: posterRes.secure_url,
        publicId: posterRes.public_id,
      };
    }
    if (visibility) {
      newCollection.visibility = visibility;
    }

    await newCollection.save();
    res.status(201).json({
      collection: {
        title,
        description,
        poster: newCollection.poster?.url,
        collectionId: newCollection._id,
        visibility: newCollection?.visibility,
      },
    });
  } catch (err) {
    res.status(500).json({ error: err });
  }
};
export const CreateCard: RequestHandler = async (req, res) => {
  const { answer, question, collectionId } = req.body;

  const ownerId = req.user.id;

  if (!answer || !question) {
    res.status(422).json({
      error: "missing answer or question",
      message: "question and answer is required to create card",
    });
    return;
  }

  try {
    const exist = await Card.findOne({
      owner: ownerId,
      question: question,
      collectionId: collectionId,
    });
    if (exist) {
      res.status(422).json({
        error: "user already has the card in his collection",
        message: "this card already exist in the collection",
      });
      return;
    }

    const newCard = new Card({
      question,
      answer,
      owner: ownerId,
      collectionId,
    });

    await newCard.save();

    // Add the new card ID to the collection's cards array
    const collection = await CardsCollection.findById(collectionId);
    if (!collection) {
      res.status(404).json({ error: "Collection not found" });
      return;
    }

    collection.cards.push(
      newCard._id as unknown as mongoose.Schema.Types.ObjectId
    );
    await collection.save();

    // Populate the collection with the newly added card
    const updatedCollection = await CardsCollection.findById(collectionId).populate({
      path: 'cards',
      select: '_id answer question collectionId'
    });

    res.status(201).json({ message: "Card added successfully", collection: updatedCollection });
  } catch (err) {
    res.status(500).json({ error: "Internal server error" });
  }
};

export const updateCardsCollection: RequestHandler = async (
  req: createCardsCollectionRequest,
  res
) => {
  const { title, description, category } = req.body;
  const ownerId = req.user.id;
  const poster = req.files?.poster as formidable.File;
  const { CardsCollectionId } = req.params;
  // const test = req.params;Z
  // console.log({ test, ownerId });
  const newCardsCollection = await CardsCollection.findOneAndUpdate(
    {
      owner: ownerId,
      _id: CardsCollectionId,
    },
    {
      title,
      description,
      category,
    },
    {
      new: true,
    }
  );

  if (!newCardsCollection) {
    res.status(404).json({
      error: "Collection not found",
      message: " collection not found ",
    });
    return;
  }
  if (poster) {
    if (newCardsCollection.poster?.publicId) {
      await cloudinary.uploader.destroy(newCardsCollection.poster?.publicId);
    }
    const posterRes = await cloudinary.uploader.upload(poster.filepath, {
      width: 300,
      height: 300,
      crop: "thumb",
      gravity: "face",
    });
    newCardsCollection.poster = {
      url: posterRes.secure_url,
      publicId: posterRes.public_id,
    };
    await newCardsCollection.save();
  }

  res.status(201).json({
    collection: {
      title,
      description,
      poster: newCardsCollection.poster?.url,
      collectionId: newCardsCollection._id,
    },
  });
};
export const updateCard: RequestHandler = async (req, res) => {
  const { answer, question, collectionId } = req.body;
  const ownerId = req.user.id;
  const { cardId } = req.params;
  // const test = req.params;Z
  // console.log({ test, ownerId });
  const newCard = await Card.findOneAndUpdate(
    {
      owner: ownerId,
      _id: cardId,
      collectionId: collectionId,
    },
    {
      answer,
      question,
    },
    {
      new: true,
    }
  );

  if (!newCard) {
    res.status(404).json({
      error: "card not found",
      message: " card not found ",
    });
    return;
  }

  res.status(201).json({
    card: {
      answer,
      question,
      collectionId,
      cardId: newCard._id,
    },
  });
};

export const getCard: RequestHandler = async (req, res) => {
  const { collectionId } = req.params;

  if (!collectionId) {
    res.status(400).json({ error: "Collection ID is required" });
    return;
  }

  try {
    const cards = await Card.find({ collectionId });

    if (!cards.length) {
      res.status(404).json({ error: "No cards found for this collection" });
      return;
    }

    res.json({ cards });
  } catch (err) {
    res.status(500).json({ error: "Internal server error" });
  }
};
export const deleteCard: RequestHandler = async (req, res) => {
  const { collectionId, cardId } = req.params;

  if (!collectionId || !cardId) {
    res.status(400).json({ error: "Collection ID and Card ID are required" });
    return;
  }

  try {
    const card = await Card.findOneAndDelete({ _id: cardId, collectionId });

    if (!card) {
      res.status(404).json({ error: "Card not found in this collection" });
      return;
    }

    // Remove the card ID from the collection's cards array
    const collection = await CardsCollection.findById(collectionId);
    if (collection) {
      collection.cards = collection.cards.filter(
        (card) => card.toString() !== cardId.toString()
      );
      await collection.save();
    }

    res.json({ message: "Card deleted successfully" });
  } catch (err) {
    res.status(500).json({ error: "Internal server error" });
  }
};

export const getLatestCollection: RequestHandler = async (req, res) => {
  const list = await CardsCollection.find()
    .sort("-createdAt")
    .limit(10)
    .populate<PopulateFavList>("owner");

  const collection = list.map((item) => {
    return {
      id: item._id,
      title: item.title,
      description: item.description,
      category: item.category,
      poster: item.poster?.url,
      owner: {
        name: item.owner.name,
        id: item.owner._id,
        avatar: item.owner.avatar.url,
      },
    };
  });

  res.json({ collection });
};

export const getCollectionWithCards: RequestHandler = async (req, res) => {
  const { collectionId } = req.params;

  if (!collectionId) {
    res.status(400).json({ error: "Collection ID is required" });
    return;
  }

  try {
    const collection = await CardsCollection.findById(collectionId).populate({
      path: "cards",
      select: "_id answer question collectionId",
    });

    if (!collection) {
      res.status(404).json({ error: "Collection not found" });
      return;
    }

    res.json(collection);
  } catch (err) {
    res.status(500).json({ error: "Internal server error" });
  }
};
