import AutogeneratedPlaylist from "#/models/autoGeneratedPlaylist";
import CardsCollection from "#/models/cardsCollection";
import { RequestHandler } from "express";
import cron from "node-cron";

const generatePlaylist = async () => {
  const result = await CardsCollection.aggregate([
    { $sort: { likes: -1 } },
    {
      $sample: { size: 20 },
    },
    {
      $group: {
        _id: "$category",
        cardscollections: { $push: "$$ROOT._id" },
      },
    },
  ]);
  result.map(async (item) => {
    await AutogeneratedPlaylist.updateOne(
      {
        title: item._id,
      },
      {
        $set: { items: item.cardscollections },
      },
      {
        upsert: true,
      }
    );
  });
};

cron.schedule("*/2 * * * *", async () => {
  // this will run every 24 hours
  await generatePlaylist();
});
