import { Model, model, models, ObjectId, Schema } from "mongoose";

interface autoPlaylistDocument {
  title: string;
  items: ObjectId[];
}

const autoGeneratedPlaylistSchema = new Schema<autoPlaylistDocument>(
  {
    title: {
      type: String,
      required: true,
    },
    items: [
      {
        type: Schema.Types.ObjectId,
        required: true,
        ref: "CardsCollection",
      },
    ],
  },
  {
    timestamps: true,
  }
);

const AutoGeneratedPlaylist =
  models.AutoGeneratedPlaylist ||
  model("AutoGeneratedPlaylist", autoGeneratedPlaylistSchema);
export default AutoGeneratedPlaylist as Model<autoPlaylistDocument>;
